ApiVersion = {
    "PROD_MON_BUREAU_NUMERIQUE": "3.7.14",
    "PROD_MON_ENT_OCCITANIE": "3.7.14",
    "PROD_ARSENE76": "3.7.14",
    "PROD_ENT27": "3.7.14",
    "PROD_ENTCREUSE": "3.7.14",
    "PROD_AUVERGNERHONEALPES": "3.7.14",
    "PROD_AGORA06": "3.7.14",
    "PROD_CYBERCOLLEGES42": "3.7.14",
    "PROD_ECOLLEGE_HAUTE_GARONNE": "3.7.14",
    "PROD_MONCOLLEGE_VALDOISE": "3.7.14",
    "PROD_WEBCOLLEGE_SEINESAINTDENIS": "3.7.14",
    "PROD_ECLAT_BFC": "3.7.14",
    "PROD_AUCOLLEGE84_VAUCLUSE": "3.7.14",
    "PROD_KOSMOS_EDUCATION": "3.7.14",
    "PROD_DEMO_SKOLENGO": "3.7.14",
    "PROD_SKOLENGO_FORMATION": "3.7.14",
    "PROD_SCHULPORTAL_OSTBELGIEN": "3.7.14",
    "PROD_ENT_VAL_DE_MARNE": "3.7.14"
}

ApiUrl = {
    "PROD_MON_BUREAU_NUMERIQUE": "https://mobilite.monbureaunumerique.fr/mobilite",
    "PROD_MON_ENT_OCCITANIE": "https://mobilite.mon-ent-occitanie.fr/mobilite",
    "PROD_ARSENE76": "https://mobilite.arsene76.fr/mobilite",
    "PROD_ENT27": "https://mobilite.ent27.fr/mobilite",
    "PROD_ENTCREUSE": "https://mobilite.entcreuse.fr/mobilite",
    "PROD_AUVERGNERHONEALPES": "https://mobilite.ent.auvergnerhonealpes.fr/mobilite",
    "PROD_AGORA06": "https://mobilite.agora06.fr/mobilite",
    "PROD_CYBERCOLLEGES42": "https://mobilite.cybercolleges42.fr/mobilite",
    "PROD_ECOLLEGE_HAUTE_GARONNE": "https://mobilite.ecollege.haute-garonne.fr/mobilite",
    "PROD_MONCOLLEGE_VALDOISE": "https://mobilite.moncollege.valdoise.fr/mobilite",
    "PROD_WEBCOLLEGE_SEINESAINTDENIS": "https://mobilite.webcollege.seinesaintdenis.fr/mobilite",
    "PROD_ECLAT_BFC": "https://mobilite.eclat-bfc.fr/mobilite",
    "PROD_KOSMOS_EDUCATION": "https://mobilite.kosmoseducation.com/mobilite",
    "PROD_AUCOLLEGE84_VAUCLUSE": "https://mobilite.aucollege84.vaucluse.fr/mobilite",
    "PROD_DEMO_SKOLENGO": "https://mobilite.demo.skolengo.com/mobilite",
    "PROD_SKOLENGO_FORMATION": "https://mobilite.formation.skolengo.com/mobilite",
    "PROD_SCHULPORTAL_OSTBELGIEN": "https://mobilite.schulen.be/mobilite",
    "PROD_ENT_VAL_DE_MARNE": "https://mobilite.entvaldemarne.skolengo.com/mobilite"
}
